module.exports = [
  {
    firstName: "Jim",
    lastName: "James",
    type: "Residential",
    contNeed: "3",
    deliveryToSchedule: "3",
    task: "On Site Storage",
    date: "17-12-2016",
    address: "4488 E. Shred Ave",
    city: "Tempe",
    state: "AZ",
    zip: "85257",
    price: 205
  }, {
    firstName: "James",
    lastName: "Murphy",
    type: "Residential",
    contNeed: "2",
    deliveryToSchedule: "2",
    task: "Warehouse Storage",
    date: "15-12-2016",
    address: "678 Shut Up And Play The Hits Blvd.",
    city: "Phoenix",
    state: "AZ",
    zip: "85260",
    price: 185
  }, {
    firstName: "Josh",
    lastName: "Tillman",
    type: "Residential",
    contNeed: "4",
    deliveryToSchedule: "4",
    task: "Curb To Curb",
    date: "15-12-2016",
    address: "333 CallMeNancy Rd.",
    city: "Cave Creek",
    state: "AZ",
    zip: "85208",
    price: 200
  }, {
    firstName: "Dan",
    lastName: "Deacon",
    type: "Residential",
    contNeed: "1",
    deliveryToSchedule: "1",
    task: "On Site Storage",
    date: "15-12-2016",
    address: "111 America St.",
    city: "Gilbert",
    state: "AZ",
    zip: "85222",
    price: 170
  }, {
    firstName: "Matt",
    lastName: "Berninger",
    type: "Residential",
    contNeed: "2",
    deliveryToSchedule: "2",
    task: "Curb To Curb",
    date: "15-12-2016",
    address: "8628 Boxer Rd.",
    city: "Chandler",
    state: "AZ",
    zip: "85772",
    price: 230
  }, {
    firstName: "Zach",
    lastName: "Condon",
    type: "Residential",
    contNeed: "1",
    deliveryToSchedule: "1",
    task: "Warehouse Storage",
    date: "15-12-2016",
    address: "36 FlyingClubCup Ln.",
    city: "Tucson",
    state: "AZ",
    zip: "85642",
    price: 162
  }, {
    firstName: "Andrew",
    lastName: "Bird",
    type: "Residential",
    contNeed: "1",
    deliveryToSchedule: "1",
    task: "On Site Storage",
    date: "19-12-2016",
    address: "36 Whistle Rd.",
    city: "Flagstaff",
    state: "AZ",
    zip: "85888",
    price: 199
  }, {
    firstName: "Kevin",
    lastName: "Morby",
    type: "Residential",
    contNeed: "1",
    deliveryToSchedule: "1",
    task: "Curb To Curb",
    date: "16-12-2016",
    address: "92 The Mountain Ave.",
    city: "Chadler",
    state: "AZ",
    zip: "85582",
    price: 159
  }
];
